name: Quality Gates

on:
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  quality:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-quality-gates.yml@v2.4.0
    with:
      java-version: "21"
      coverage-command: >-
        ./gradlew qualityCoverage
        --no-daemon --stacktrace